/**
 * Inline Portuguese/English fallback messages used when i18n keys are not
 * resolved at render time (dev mode). Kept separate from the component so
 * the visual layer is not polluted by long string tables.
 */

export const DASHBOARD_FALLBACK_MESSAGES: Record<string, string> = {
  totalStudentsTitle: "Total Students",
  totalStudentsFooter: "+12 este mês",
  biometricsLoggedTitle: "Biometrias registadas",
  biometricsLoggedFooter: "Este ano letivo",
  activeAlertsTitle: "Alertas ativos",
  activeAlertsFooter: "1 prioridade crítica",
  pendingAssessmentsTitle: "Avaliações pendentes",
  pendingAssessmentsFooter: "5 em atraso",
  title: "Painel",
  dashboardStatus: "Painel",
  overview: "Vista geral",
  welcomeBackOverview:
    "Bem-vindo de volta, {name}. Aqui tens a tua visao geral de hoje.",
  platformOverview:
    "Centro de comando institucional para cobertura, segurança e qualidade dos dados.",
  teacherOverview:
    "Espaço de trabalho para registos de turma, dispensas e sinais SOS.",
  psychologistOverview:
    "Triagem de acompanhamento, instrumentos recentes e casos sinalizados.",
  parentOverview: "Resumo familiar dos alunos associados e relatórios partilhados.",
  activitySummary: "Últimos registos, próximos passos e atalhos do teu percurso.",
  unlinkedTitle: "Perfil não associado",
  unlinkedDescription:
    "A tua conta ainda não está associada a um perfil de aluno. Contacta a escola para concluírem a ligação.",
  students: "Alunos",
  classes: "Turmas",
  sessions: "Sessões",
  pendingSos: "SOS pendentes",
  totalRegistered: "Total registados",
  activeClasses: "Turmas ativas",
  evaluationsDone: "Sessões registadas",
  alertsPending: "SOS em aberto",
  questionnairesAvailable: "Questionários",
  questionnaireQueue: "Submissões para leitura",
  studentsInFollowUp: "Em acompanhamento",
  studentsInFollowUpDesc: "Alunos com sinais recentes",
  linkedStudents: "Alunos associados",
  linkedStudentsDesc: "Alunos ligados à tua conta",
  reportsAvailable: "Relatórios",
  reportsAvailableDesc: "Documentos disponíveis",
  familyQuestionnairesDesc: "Questionários submetidos",
  teacherStudentsDesc: "Alunos no ano letivo atual",
  teacherSessionsDesc: "Sessões que registaste",
  activeExemptions: "Dispensas ativas",
  activeExemptionsDesc: "Dispensas em vigor",
  teacherSosDesc: "Alertas encaminhados para ti",
  missingBiometrics: "Biometrias em falta",
  missingBiometricsDesc: "Alunos sem medição no ano atual",
  missingTests: "Testes em falta",
  missingTestsDesc: "Alunos sem prova física no ano atual",
  missingQuestionnaires: "Questionários em falta",
  missingQuestionnairesDesc: "Alunos sem submissão no ano atual",
  unlinkedStudents: "Alunos sem conta",
  unlinkedStudentsDesc: "Perfis ainda sem utilizador associado",
  guardianLinks: "Ligações familiares",
  guardianLinksDesc: "Associações aluno-encarregado",
  auditLast7Days: "Auditoria recente",
  auditLast7DaysDesc: "Eventos registados nos últimos 7 dias",
  reportsLast30Days: "Relatórios recentes",
  reportsLast30DaysDesc: "Relatórios gerados nos últimos 30 dias",
  commandCenter: "Comando",
  commandCenterTitle: "Prioridades institucionais",
  commandCenterDescription:
    "O que precisa de decisão, revisão ou encaminhamento neste momento.",
  teacherDesk: "Aula e registos",
  teacherDeskTitle: "Fila de trabalho da turma",
  teacherDeskDescription:
    "Alunos e registos que ajudam a fechar a cobertura do período.",
  clinicalDesk: "Acompanhamento",
  clinicalDeskTitle: "Fila de intervenção",
  clinicalDeskDescription: "Casos SOS por resolver, ordenados pelos mais antigos.",
  familyDesk: "Família",
  familyDeskTitle: "Acompanhamento por aluno",
  familyDeskDescription: "Leitura simples dos últimos sinais partilhados pela escola.",
  studentDesk: "Percurso",
  studentDeskTitle: "O teu estado atual",
  studentDeskDescription: "Datas e atalhos principais para continuares o teu registo.",
  quickActions: "Ações rápidas",
  quickActionsDescription: "Atalhos diretos para as tarefas mais prováveis.",
  recentActivity: "Atividade recente",
  viewAll: "Ver tudo",
  systemStatus: "Estado do sistema",
  allSystemsOperational: "Todos os sistemas operacionais",
  draftsSyncing: "{count} rascunhos a sincronizar",
  lastSync: "Ultima sincronizacao",
  allCaughtUp: "Tudo em dia",
  bmiFitnessTrends: "Tendencias de IMC e condicao fisica",
  currentAcademicYear: "Ano letivo atual",
  avgBmi: "IMC medio",
  fitnessScore: "Score fisico",
  zafDistributionTitle: "Distribuicao ZAF",
  coverageAverageLabel: "Media da turma",
  dataQualityTitle: "Cobertura e qualidade",
  dataQualityDescription: "Lacunas do ano letivo atual que merecem seguimento.",
  zafTitle: "Zona saudável e evolução",
  zafDescription: "Cobertura biométrica e distribuição ZAF nos anos recentes.",
  recentReportsTitle: "Relatórios recentes",
  recentReportsDescription: "Últimos documentos disponibilizados pela escola.",
  recentQuestionnairesTitle: "Instrumentos recentes",
  recentQuestionnairesDescription: "Submissões mais recentes para leitura clínica.",
  noPendingCasesTitle: "Sem casos pendentes",
  noPendingCasesDescription: "A fila SOS está limpa neste momento.",
  noRecentQuestionnairesTitle: "Sem questionários recentes",
  noRecentQuestionnairesDescription:
    "As novas submissões aparecem aqui quando forem recebidas.",
  noLinkedStudentsDashboardTitle: "Sem alunos associados",
  noLinkedStudentsDashboardDescription:
    "Quando a escola concluir a associação, os dados surgem aqui.",
  noReportsDashboardTitle: "Sem relatórios recentes",
  noReportsDashboardDescription:
    "Os relatórios disponibilizados pela escola aparecem nesta área.",
  classPending: "Turma por confirmar",
  alertOpenedOn: "Aberto em {date}",
  generatedOn: "Gerado em {date}",
  studentRecord: "Registo do aluno",
  lastBiometric: "Última biometria",
  lastTests: "Últimos testes",
  lastQuestionnaire: "Último questionário",
  lastReport: "Último relatório",
  activeStudentSos: "SOS ativo",
  activeStudentExemption: "Dispensa ativa",
  noStudentSignal: "Sem sinal ativo",
  lastMeasurement: "Data da última medição",
  lastTestDate: "Data do último teste físico",
  studentQuestionnairesDesc: "Instrumentos já submetidos",
  needsBiometrics: "Registar biometria",
  needsTests: "Registar testes",
  reviewItem: "Rever",
  openItem: "Abrir",
  latestAcademicYear: "Último ano letivo",
  coverageLabel: "Cobertura registada",
  studentsWithBiometrics: "Com biometria",
  healthyStudentsLabel: "Em Z. Saudável",
  improvementStudentsLabel: "Em Z. Melhoria",
  zsaf: "Z. Saudável",
  zmf: "Z. Melhoria",
  noBioData: "Sem dados biométricos",
  annualSeriesPendingTitle: "Ainda não existe série histórica comparável.",
  annualSeriesPendingDescription:
    "A evolução anual aparece quando houver mais do que um ano letivo com biometria registada.",
  studentsUnit: "alunos",
  actionSosTitle: "SOS",
  actionSosDesc: "Rever alertas ativos",
  actionStudentsTitle: "Alunos",
  actionStudentsDesc: "Gerir perfis e ligações",
  actionClassTitle: "Turma",
  actionClassDesc: "Ver trabalho da turma",
  actionBiometricsTitle: "Biometria",
  actionBiometricsDesc: "Registar medições",
  actionTestsTitle: "Testes",
  actionTestsDesc: "Registar provas",
  actionReportsTitle: "Relatórios",
  actionReportsDesc: "Consultar ou gerar documentos",
  actionQuestionnairesTitle: "Questionários",
  actionQuestionnairesDesc: "Responder instrumentos",
  actionProtocolsTitle: "Protocolos",
  actionProtocolsDesc: "Consultar orientações",
  actionAdminTitle: "Admin",
  actionAdminDesc: "Gerir utilizadores",
  actionAuditTitle: "Auditoria",
  actionAuditDesc: "Rever atividade",
  actionProfileTitle: "Perfil",
  actionProfileDesc: "Preferências e conta",
  actionLogBiometricsTitle: "Registar biometria",
  actionLogBiometricsDesc: "Registar dados do aluno",
  actionRaiseSosTitle: "Abrir SOS",
  actionRaiseSosDesc: "Alerta de emergencia",
  actionNewAssessmentTitle: "Nova avaliacao",
  actionNewAssessmentDesc: "Atribuir questionario",
  actionGenerateReportTitle: "Gerar relatorio",
  actionGenerateReportDesc: "Exportar relatorio PDF",
  actionEnrollStudentTitle: "Inscrever aluno",
  actionEnrollStudentDesc: "Adicionar novo aluno",
  actionBulkImportTitle: "Importacao em lote",
  actionBulkImportDesc: "Upload CSV",
  studentHealthProgress: "My Health Progress",
  studentGrowthSubtitle: "Tracking your growth over time",
  student6Months: "6 Months",
  student1Year: "1 Year",
  studentWeightLabel: "Weight (kg)",
  studentHeightLabel: "Height (cm)",
  studentPendingTasks: "Pending Tasks",
  studentNoPendingTasks: "No pending tasks",
  studentNoPendingDesc: "All questionnaires for this school year have been submitted.",
  studentStart: "Start",
  studentDueSoon: "Due Soon",
  studentPending: "Pending",
  studentYourPosition: "Your Position",
  studentComparedWHO: "Position relative to the healthy zone",
  studentPercentile: "Percentile",
  studentCurrentHealth: "Current Health Status",
  studentBMI: "BMI",
  studentHeight: "Height",
  studentWeight: "Weight",
  studentZScore: "Z-Score (BMI)",
  studentFitnessScore: "Fitness Score",
  studentNoBiometrics: "No biometric data recorded",
  studentNoBiometricsDesc: "Once your teacher records your measurements, data will appear here.",
  studentNoTests: "No tests recorded",
  studentLastUpdated: "Last updated",
  studentHealthy: "Healthy",
  studentAtRisk: "At Risk",
  studentNormal: "Normal",
  studentGood: "Good",
  studentSosActive: "Active SOS alert",
};

export const DASHBOARD_FALLBACK_NAV: Record<string, string> = {
  perfil: "Perfil",
};

export const DASHBOARD_FALLBACK_QUESTIONNAIRES: Record<string, string> = {
  autoconceito: "Autoconceito",
  autoestima: "Autoestima",
  kidmed: "KIDMED",
};
